// API: Seed - Datos iniciales del Directorio Digital
// POST - Poblar la base de datos con datos de ejemplo

import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { hashPassword } from '@/lib/auth';

export async function POST() {
  try {
    // Check if data already exists
    const categoryCount = await db.category.count();
    if (categoryCount > 0) {
      return NextResponse.json(
        { success: false, error: 'La base de datos ya tiene datos. Usa el panel de administración para gestionar.' },
        { status: 409 }
      );
    }

    // 1. Create Admin user
    const hashedPassword = await hashPassword('Admin123!');
    await db.admin.create({
      data: {
        email: 'admin@huastecadigital.com',
        password: hashedPassword,
        name: 'Administrador General',
        role: 'SUPER_ADMIN',
      },
    });

    // 2. Create Categories
    const categories = await Promise.all([
      db.category.create({ data: { name: 'Restaurantes', slug: 'restaurantes', icon: 'UtensilsCrossed', description: 'Restaurantes, fondas y comedores de la región', color: '#DC2626', order: 1 } }),
      db.category.create({ data: { name: 'Abarrotes y Tiendas', slug: 'abarrotes', icon: 'ShoppingBasket', description: 'Tiendas de abarrotes y miscellaneous', color: '#EA580C', order: 2 } }),
      db.category.create({ data: { name: 'Salud y Farmacias', slug: 'salud', icon: 'Heart', description: 'Servicios médicos, farmacias y consultorios', color: '#16A34A', order: 3 } }),
      db.category.create({ data: { name: 'Educación', slug: 'educacion', icon: 'GraduationCap', description: 'Escuelas, academias y centros educativos', color: '#2563EB', order: 4 } }),
      db.category.create({ data: { name: 'Servicios Profesionales', slug: 'servicios-profesionales', icon: 'Briefcase', description: 'Servicios profesionales y consultorías', color: '#7C3AED', order: 5 } }),
      db.category.create({ data: { name: 'Construcción y Materiales', slug: 'construccion', icon: 'HardHat', description: 'Materiales de construcción y servicios de obra', color: '#B45309', order: 6 } }),
      db.category.create({ data: { name: 'Tecnología', slug: 'tecnologia', icon: 'Monitor', description: 'Servicios de tecnología y reparación', color: '#0891B2', order: 7 } }),
      db.category.create({ data: { name: 'Belleza y Cuidado Personal', slug: 'belleza', icon: 'Scissors', description: 'Salones de belleza, barberías y spas', color: '#DB2777', order: 8 } }),
      db.category.create({ data: { name: 'Automotriz', slug: 'automotriz', icon: 'Car', description: 'Talleres mecánicos, refacciones y autos', color: '#4B5563', order: 9 } }),
      db.category.create({ data: { name: 'Turismo y Hospedaje', slug: 'turismo', icon: 'Palmtree', description: 'Hoteles, cabañas y tours turísticos', color: '#059669', order: 10 } }),
      db.category.create({ data: { name: 'Alimentos y Bebidas', slug: 'alimentos', icon: 'Coffee', description: 'Cafeterías, panaderías y negocios de alimentos', color: '#92400E', order: 11 } }),
      db.category.create({ data: { name: 'Entretenimiento', slug: 'entretenimiento', icon: 'Music', description: 'Eventos, música y entretenimiento', color: '#6D28D9', order: 12 } }),
    ]);

    // 3. Create Plans
    await Promise.all([
      db.plan.create({
        data: {
          name: 'Gratuito',
          slug: 'gratuito',
          type: 'GRATUITO',
          price: 0,
          description: 'Presencia básica en el directorio digital. Ideal para empezar a darte a conocer en la Huasteca.',
          features: 'Listado en el directorio|Nombre y categoría|Teléfono y dirección|Estado de aprobación',
          icon: 'Package',
          color: '#6B7280',
          popular: false,
          order: 1,
        },
      }),
      db.plan.create({
        data: {
          name: 'Landing Page',
          slug: 'landing-page',
          type: 'LANDING_PAGE',
          price: 299,
          description: 'Página web personalizada para tu negocio. Destaca entre la competencia con presencia profesional.',
          features: 'Todo lo del plan Gratuito|Página web personalizada|Listado destacado con badge|Enlace directo a WhatsApp|Redes sociales vinculadas|Logo e imagen del negocio|Coordenadas para mapa',
          icon: 'Layout',
          color: '#059669',
          popular: false,
          order: 2,
        },
      }),
      db.plan.create({
        data: {
          name: 'Chatbot IA',
          slug: 'chatbot',
          type: 'CHATBOT',
          price: 499,
          description: 'Atención automática 24/7 con inteligencia artificial. Nunca más pierdas un cliente por falta de respuesta.',
          features: 'Todo lo del plan Landing Page|Chatbot con IA integrado|Atención automática 24/7|Respuestas personalizadas|Derivación a WhatsApp|Panel de conversaciones|Métricas de atención',
          icon: 'Bot',
          color: '#7C3AED',
          popular: true,
          order: 3,
        },
      }),
      db.plan.create({
        data: {
          name: 'Menú Digital',
          slug: 'menu-digital',
          type: 'MENU_DIGITAL',
          price: 399,
          description: 'Menú digital con código QR para restaurantes. Actualiza tus platillos cuando quieras sin costos de impresión.',
          features: 'Todo lo del plan Gratuito|Menú digital con QR|Platillos con fotos y precios|Categorías de menú|Actualizaciones ilimitadas|Diseño responsive|Código QR personalizable',
          icon: 'UtensilsCrossed',
          color: '#DC2626',
          popular: false,
          order: 4,
        },
      }),
    ]);

    // 4. Create Sample Businesses
    const sampleBusinesses = [
      {
        name: 'Restaurante La Huasteca',
        categoryId: categories[0].id,
        logo: null,
        description: 'Auténtica comida huasteca con enchiladas huastecas, bocoles, zacahuil y tamales. Sabor tradicional de la región con ingredientes frescos y locales.',
        address: 'Av. Principal #123, Centro',
        city: 'Huejutla de Reyes',
        phone: '789 123 4567',
        whatsapp: '527891234567',
        facebook: 'https://facebook.com/restauranteLahuasteca',
        instagram: '@restauranteLahuasteca',
        website: null,
        latitude: 21.1425,
        longitude: -98.4183,
        status: 'APPROVED' as const,
        featured: true,
      },
      {
        name: 'Farmacia San Miguel',
        categoryId: categories[2].id,
        logo: null,
        description: 'Farmacia con más de 20 años de servicio en la Huasteca. Medicamentos, productos de higiene personal y asesoría farmacéutica profesional.',
        address: 'Calle Hidalgo #45, Col. Centro',
        city: 'Huejutla de Reyes',
        phone: '789 234 5678',
        whatsapp: '527892345678',
        facebook: 'https://facebook.com/farmaciasanmiguel',
        instagram: null,
        website: null,
        latitude: 21.1408,
        longitude: -98.4175,
        status: 'APPROVED' as const,
        featured: false,
      },
      {
        name: 'Cyber Cómputo Huasteca',
        categoryId: categories[6].id,
        logo: null,
        description: 'Servicios de reparación de computadoras, venta de accesorios, impresión, copias y servicios de internet. Atención rápida y profesional.',
        address: 'Av. Juárez #89, Local 3',
        city: 'Huejutla de Reyes',
        phone: '789 345 6789',
        whatsapp: '527893456789',
        facebook: 'https://facebook.com/cybercomputohuasteca',
        instagram: '@cybercomputo',
        website: null,
        latitude: null,
        longitude: null,
        status: 'APPROVED' as const,
        featured: false,
      },
      {
        name: 'Salón de Belleza Esmeralda',
        categoryId: categories[7].id,
        logo: null,
        description: 'Salón de belleza completo: corte de cabello, tintes, maquillaje profesional, uñas, tratamientos capilares y spa. Ambiente relajante y profesional.',
        address: 'Calle Morelos #56, Col. Centro',
        city: 'Huejutla de Reyes',
        phone: '789 456 7890',
        whatsapp: '527894567890',
        facebook: 'https://facebook.com/salonbellezaesmeralda',
        instagram: '@salonesmeralda',
        website: null,
        latitude: 21.1410,
        longitude: -98.4190,
        status: 'APPROVED' as const,
        featured: true,
      },
      {
        name: 'Talleres Mecánicos del Valle',
        categoryId: categories[8].id,
        logo: null,
        description: 'Taller mecánico integral para todo tipo de vehículos. Servicio de motor, transmisión, frenos, suspensión y eléctrico. Más de 15 años de experiencia.',
        address: 'Carretera Huejutla-Jaltocán Km 2',
        city: 'Huejutla de Reyes',
        phone: '789 567 8901',
        whatsapp: '527895678901',
        facebook: null,
        instagram: null,
        website: null,
        latitude: 21.1380,
        longitude: -98.4250,
        status: 'APPROVED' as const,
        featured: false,
      },
      {
        name: 'Hotel Posada Huasteca',
        categoryId: categories[9].id,
        logo: null,
        description: 'Hotel con habitaciones cómodas y limpias, restaurante propio, estacionamiento y wifi gratis. Ubicación céntrica cerca de los principales atractivos turísticos.',
        address: 'Av. Insurgentes #200, Centro',
        city: 'Huejutla de Reyes',
        phone: '789 678 9012',
        whatsapp: '527896789012',
        facebook: 'https://facebook.com/hotelposadahuasteca',
        instagram: '@posadahuasteca',
        website: 'https://posadahuasteca.com',
        latitude: 21.1430,
        longitude: -98.4200,
        status: 'APPROVED' as const,
        featured: true,
      },
      {
        name: 'Panadería El Trigo Dorado',
        categoryId: categories[10].id,
        logo: null,
        description: 'Pan artesanal horneado diariamente. Pan dulce, pan de mesa, pasteles para toda ocasión y repostería fina. Tradición horneada con amor.',
        address: 'Calle Guerrero #34, Col. Centro',
        city: 'Huejutla de Reyes',
        phone: '789 789 0123',
        whatsapp: '527897890123',
        facebook: 'https://facebook.com/panaderiaeltrigodorado',
        instagram: '@eltrigodorado',
        website: null,
        latitude: null,
        longitude: null,
        status: 'APPROVED' as const,
        featured: false,
      },
      {
        name: 'Lic. María García - Abogada',
        categoryId: categories[4].id,
        logo: null,
        description: 'Servicios jurídicos profesionales: derecho civil, familiar, mercantil y agrario. Asesoría legal confiable con amplia experiencia en la región huasteca.',
        address: 'Av. Juárez #156, Despacho 201',
        city: 'Huejutla de Reyes',
        phone: '789 890 1234',
        whatsapp: '527898901234',
        facebook: null,
        instagram: null,
        website: null,
        latitude: 21.1415,
        longitude: -98.4188,
        status: 'APPROVED' as const,
        featured: false,
      },
      {
        name: 'Materiales La Construcción',
        categoryId: categories[5].id,
        logo: null,
        description: 'Todo para construcción: cemento, varilla, block, arena, grava, pintura y herramientas. Precios competitivos y entrega a domicilio en la región.',
        address: 'Carretera México-Tampico Km 180',
        city: 'Huejutla de Reyes',
        phone: '789 901 2345',
        whatsapp: '527899012345',
        facebook: 'https://facebook.com/materialeslaconstruccion',
        instagram: null,
        website: null,
        latitude: 21.1360,
        longitude: -98.4300,
        status: 'APPROVED' as const,
        featured: false,
      },
      {
        name: 'Academia de Música Huasteca',
        categoryId: categories[11].id,
        logo: null,
        description: 'Clases de guitarra, violín, acordeón y huapanguera. Talleres de son huasteco y tradicional. Grupos para eventos y fiestas regionales.',
        address: 'Calle Zaragoza #78',
        city: 'Huejutla de Reyes',
        phone: '789 012 3456',
        whatsapp: '527890123456',
        facebook: 'https://facebook.com/musicahuasteca',
        instagram: '@musicahuasteca',
        website: null,
        latitude: null,
        longitude: null,
        status: 'APPROVED' as const,
        featured: true,
      },
      {
        name: 'Abarrotes Doña Chelo',
        categoryId: categories[1].id,
        logo: null,
        description: 'Tienda de abarrotes con productos básicos, frutas y verduras de la región, carnes frías y productos de limpieza. Atención amable desde 1995.',
        address: 'Calle Madero #12, Col. El Mirador',
        city: 'Huejutla de Reyes',
        phone: '789 123 4560',
        whatsapp: '527891234560',
        facebook: null,
        instagram: null,
        website: null,
        latitude: null,
        longitude: null,
        status: 'APPROVED' as const,
        featured: false,
      },
      {
        name: 'Centro Educativo Huasteca',
        categoryId: categories[3].id,
        logo: null,
        description: 'Institución educativa con niveles de preescolar, primaria y secundaria. Educación de calidad con enfoque bilingüe y valores humanos.',
        address: 'Av. Universidad #300',
        city: 'Huejutla de Reyes',
        phone: '789 234 5670',
        whatsapp: '527892345670',
        facebook: 'https://facebook.com/centroeducativohuasteca',
        instagram: '@cehuasteca',
        website: 'https://cehuasteca.edu.mx',
        latitude: 21.1450,
        longitude: -98.4150,
        status: 'APPROVED' as const,
        featured: false,
      },
      {
        name: 'Café La Sierra',
        categoryId: categories[10].id,
        logo: null,
        description: 'Café de especialidad cultivado en las sierras de la Huasteca. Bebidas calientes y frías, repostería y un ambiente acogedor con vista panorámica.',
        address: 'Calle 5 de Mayo #22, Centro',
        city: 'Huejutla de Reyes',
        phone: '789 345 6780',
        whatsapp: '527893456780',
        facebook: 'https://facebook.com/cafelasierra',
        instagram: '@cafelasierra',
        website: null,
        latitude: 21.1420,
        longitude: -98.4195,
        status: 'APPROVED' as const,
        featured: true,
      },
      {
        name: 'Refaccionaria El Motor',
        categoryId: categories[8].id,
        logo: null,
        description: 'Refacciones para todo tipo de vehículos: automóviles, camionetas y motocicletas. Aceites, filtros, llantas y accesorios. Envíos a toda la Huasteca.',
        address: 'Av. México #150',
        city: 'Huejutla de Reyes',
        phone: '789 456 7890',
        whatsapp: '527894567890',
        facebook: 'https://facebook.com/refaccionariaelmotor',
        instagram: null,
        website: null,
        latitude: null,
        longitude: null,
        status: 'PENDING' as const,
        featured: false,
      },
    ];

    await Promise.all(
      sampleBusinesses.map(business => db.business.create({ data: business }))
    );

    return NextResponse.json({
      success: true,
      data: {
        admin: { email: 'admin@huastecadigital.com', password: 'Admin123!' },
        categories: categories.length,
        businesses: sampleBusinesses.length,
      },
    });
  } catch (error) {
    console.error('Error seeding database:', error);
    return NextResponse.json(
      { success: false, error: 'Error al poblar la base de datos' },
      { status: 500 }
    );
  }
}
